tests = "./"
task = "text-classification"
metadata = "amazon_pred.csv"
models = [
    "distilbert-base-uncased-finetuned-sst-2-english",
    "fabriceyhc/bert-base-uncased-amazon_polarity",
]
data_path = "/Users/acabrera/dev/data/sessile-main-Kvasir-SEG/"
batch_size = 16
port = 8002