name: CI Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: snok/install-poetry@v1.3
      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run tests
        run: poetry run pytest zeno
      - name: Check types
        run: make typecheck
      - name: Check Poetry
        run: make check

      - name: Build frontend
        run: |
          cd frontend/
          npm i
          npm run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/setup-node@v2
      - name: NPM install
        run: |
          cd frontend/
          npm i
      - uses: psf/black@stable
        with:
          src: "./zeno"
          version: "22.1.0"
      - uses: py-actions/flake8@v2
        with:
          path: "./zeno"
      - name: ESLint
        run: |
          cd frontend/
          eslint ./src/
